/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even - valued terms.
*/


function fibonacci(max) {
    next = 0
    first = 1
    second = 2
    sum = second
    while (next < max) {
        next = first+second
        if (next%2==0) sum += next
        first = second
        second = next
    }
    return sum
} 

console.log(fibonacci(4000000))


/**
 * 
 * (다른 풀이)
 * 
 * 피보나치 수열이 증가하는 비율은 수열이 진행될 수록 golden ratio(phi)에 가까워진다.
 * 1 1 2 3 5 8 ... 이런 식으로 증가할 때 세 번째 숫자마다 짝수다.
 * 그러므로 phi*3을 계속 곱해나가며 가장 가까운 정수들을 limit 전까지 구해 더하면 된다. 
 * 
 */
