'''
The sequence of triangle numbers is generated by adding the natural numbers. 
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
'''


import datetime
start = datetime.datetime.now()


tri_nums = [1, 3, 6, 10, 15, 21]


def next_tri():
    next_i = len(tri_nums)+1
    next_tri = tri_nums[-1] + next_i
    tri_nums.append(next_tri)
    return tri_nums


def how_many_divisor(num):
    cnt = 0
    for n in range(1, int(num**(1/2))+1):
        if num % n == 0 : cnt += 2
    if num % int(num**(1/2)) == 0 : cnt -= 1
    return cnt


def first_500_divisor():
    for i in range(6, 20000):
        next_tri()
        if how_many_divisor(tri_nums[-1]) > 500 : return tri_nums[-1]


print(first_500_divisor())
print(datetime.datetime.now() - start)
#4s
